name: Frontend CI/CD

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3

    ## install 
    - name: make build directory
      run: |
        cd ./src/front-end/timepay-front
        yarn add craco-alias
        yarn build
      env:
        CI: false
      shell:
        bash
      
    ## docker build image
    - name: 도커 이미지 빌드
      run: |
        cd ./src/front-end/timepay-front
        docker build -t ${{ secrets.DOCKER_USERNAME }}/timepay_front .
      
    ## docker hub login
    - name: Docker Hub 로그인
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    ## docker push    
    - name: Docker Hub 푸쉬
      run: docker push ${{ secrets.DOCKER_USERNAME }}/timepay_front

    ## docker compose up
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_FRONT }}
        username: ec2-user
        key: ${{ secrets.KEY }}
        script: |
          docker stop $(docker ps -a -q) 
          docker rm $(docker ps -a -q) 
          docker pull ${{ secrets.DOCKER_USERNAME }}/timepay_front

          docker run -d -p 80:80 --name tp_frontend ${{ secrets.DOCKER_USERNAME }}/timepay_front


  build-admin:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3

    ## install 
    - name: make build directory
      run: |
        cd ./src/front-end/timepay-admin
        yarn add craco-alias
        yarn build
      env:
        CI: false

      shell: bash
      
    ## docker build image
    - name: 도커 이미지 빌드
      run: |
        cd ./src/front-end/timepay-admin
        docker build -t ${{ secrets.DOCKER_USERNAME }}/timepay_admin .
      
    ## docker hub login
    - name: Docker Hub 로그인
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    ## docker push    
    - name: Docker Hub 푸쉬
      run: docker push ${{ secrets.DOCKER_USERNAME }}/timepay_admin

    ## docker compose up
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_ADMIN }}
        username: ec2-user
        key: ${{ secrets.KEY }}
        script: |
          docker stop $(docker ps -a -q) 
          docker rm $(docker ps -a -q) 
          docker pull ${{ secrets.DOCKER_USERNAME }}/timepay_admin
          docker run -d -p 80:80 --name admin_frontend ${{ secrets.DOCKER_USERNAME }}/timepay_admin

